//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcf.Client.BookServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingOutput", Namespace="http://schemas.datacontract.org/2004/07/WCF.Services.ServiceContracts")]
    [System.SerializableAttribute()]
    public partial class PingOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/WCF.Services.ServiceContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf.Client.BookServiceReference.ResultOfBookAeCEsgg9))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf.Client.BookServiceReference.ResultOfArrayOfBookAeCEsgg9))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCompleted {
            get {
                return this.IsCompletedField;
            }
            set {
                if ((this.IsCompletedField.Equals(value) != true)) {
                    this.IsCompletedField = value;
                    this.RaisePropertyChanged("IsCompleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfBookAeCEsgg9", Namespace="http://schemas.datacontract.org/2004/07/WCF.Services.ServiceContracts")]
    [System.SerializableAttribute()]
    public partial class ResultOfBookAeCEsgg9 : Wcf.Client.BookServiceReference.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcf.Client.BookServiceReference.Book DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf.Client.BookServiceReference.Book Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfArrayOfBookAeCEsgg9", Namespace="http://schemas.datacontract.org/2004/07/WCF.Services.ServiceContracts")]
    [System.SerializableAttribute()]
    public partial class ResultOfArrayOfBookAeCEsgg9 : Wcf.Client.BookServiceReference.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcf.Client.BookServiceReference.Book[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf.Client.BookServiceReference.Book[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/WCF.Services.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FrontPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FrontPage {
            get {
                return this.FrontPageField;
            }
            set {
                if ((object.ReferenceEquals(this.FrontPageField, value) != true)) {
                    this.FrontPageField = value;
                    this.RaisePropertyChanged("FrontPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wpf.book.core", ConfigurationName="BookServiceReference.IBookService")]
    public interface IBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/Ping", ReplyAction="http://wpf.book.core/IBookService/PingResponse")]
        Wcf.Client.BookServiceReference.PingOutput Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/Ping", ReplyAction="http://wpf.book.core/IBookService/PingResponse")]
        System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.PingOutput> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/GetAllBook", ReplyAction="http://wpf.book.core/IBookService/GetAllBookResponse")]
        Wcf.Client.BookServiceReference.ResultOfArrayOfBookAeCEsgg9 GetAllBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/GetAllBook", ReplyAction="http://wpf.book.core/IBookService/GetAllBookResponse")]
        System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.ResultOfArrayOfBookAeCEsgg9> GetAllBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/GetBookByISBN", ReplyAction="http://wpf.book.core/IBookService/GetBookByISBNResponse")]
        Wcf.Client.BookServiceReference.ResultOfBookAeCEsgg9 GetBookByISBN(string ISBN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/GetBookByISBN", ReplyAction="http://wpf.book.core/IBookService/GetBookByISBNResponse")]
        System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.ResultOfBookAeCEsgg9> GetBookByISBNAsync(string ISBN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/GetBookById", ReplyAction="http://wpf.book.core/IBookService/GetBookByIdResponse")]
        Wcf.Client.BookServiceReference.ResultOfBookAeCEsgg9 GetBookById(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/GetBookById", ReplyAction="http://wpf.book.core/IBookService/GetBookByIdResponse")]
        System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.ResultOfBookAeCEsgg9> GetBookByIdAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/AddBook", ReplyAction="http://wpf.book.core/IBookService/AddBookResponse")]
        Wcf.Client.BookServiceReference.Result AddBook(Wcf.Client.BookServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/AddBook", ReplyAction="http://wpf.book.core/IBookService/AddBookResponse")]
        System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.Result> AddBookAsync(Wcf.Client.BookServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/DeleteBook", ReplyAction="http://wpf.book.core/IBookService/DeleteBookResponse")]
        Wcf.Client.BookServiceReference.Result DeleteBook(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/DeleteBook", ReplyAction="http://wpf.book.core/IBookService/DeleteBookResponse")]
        System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.Result> DeleteBookAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/DeleteAll", ReplyAction="http://wpf.book.core/IBookService/DeleteAllResponse")]
        Wcf.Client.BookServiceReference.Result DeleteAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wpf.book.core/IBookService/DeleteAll", ReplyAction="http://wpf.book.core/IBookService/DeleteAllResponse")]
        System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.Result> DeleteAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceChannel : Wcf.Client.BookServiceReference.IBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<Wcf.Client.BookServiceReference.IBookService>, Wcf.Client.BookServiceReference.IBookService {
        
        public BookServiceClient() {
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wcf.Client.BookServiceReference.PingOutput Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.PingOutput> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public Wcf.Client.BookServiceReference.ResultOfArrayOfBookAeCEsgg9 GetAllBook() {
            return base.Channel.GetAllBook();
        }
        
        public System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.ResultOfArrayOfBookAeCEsgg9> GetAllBookAsync() {
            return base.Channel.GetAllBookAsync();
        }
        
        public Wcf.Client.BookServiceReference.ResultOfBookAeCEsgg9 GetBookByISBN(string ISBN) {
            return base.Channel.GetBookByISBN(ISBN);
        }
        
        public System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.ResultOfBookAeCEsgg9> GetBookByISBNAsync(string ISBN) {
            return base.Channel.GetBookByISBNAsync(ISBN);
        }
        
        public Wcf.Client.BookServiceReference.ResultOfBookAeCEsgg9 GetBookById(long id) {
            return base.Channel.GetBookById(id);
        }
        
        public System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.ResultOfBookAeCEsgg9> GetBookByIdAsync(long id) {
            return base.Channel.GetBookByIdAsync(id);
        }
        
        public Wcf.Client.BookServiceReference.Result AddBook(Wcf.Client.BookServiceReference.Book book) {
            return base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.Result> AddBookAsync(Wcf.Client.BookServiceReference.Book book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public Wcf.Client.BookServiceReference.Result DeleteBook(long id) {
            return base.Channel.DeleteBook(id);
        }
        
        public System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.Result> DeleteBookAsync(long id) {
            return base.Channel.DeleteBookAsync(id);
        }
        
        public Wcf.Client.BookServiceReference.Result DeleteAll() {
            return base.Channel.DeleteAll();
        }
        
        public System.Threading.Tasks.Task<Wcf.Client.BookServiceReference.Result> DeleteAllAsync() {
            return base.Channel.DeleteAllAsync();
        }
    }
}
